### ISSUE TITLE
[BUG]: 사용자 정보 업데이트 api 수정 요청

### ISSUE THREAD

**Issue by OseungKwon** [J-hoplin1/Online-Judge-System-Main#6]
## 요청사항
- 사용자 정보 업데이트 api(`/user/profile`) 수정 요청
- response, requeset filed에 `nickname`, `password`, `github`, `blog`가 존재하는데 따로 비밀번호 업데이트 api가 존재하는걸로 보아, `password` 대신 `message`가 있어야 할 것 같습니다.
## 설명
![image](https://github.com/J-hoplin1/Online-Judge-System-Main/assets/54261116/1007ab2b-1179-478c-b85d-22c233aa0eb9)

**Comment by J-hoplin1** [comment]
Password를 요구하는것은 정보변경시 비밀번호를 물어보고 변경하기위해서 추가한 필드입니다! Message필드는 누락된거같아 추가하도록 하겠습니다
